### ISSUE TITLE
Grouping stopped

### ISSUE THREAD

**Issue by wdenton** [purcell/ibuffer-vc#10]
Some time about a month ago the grouping stopped. Everything is under [Default]. I can't figure out what did it. It was near the lastest release, but I don't know if that did it. 

I don't even know how I can debug it. Is there a variable or function that would tell me more? Running `ibuffer-vc-set-filter-groups-by-vc-root` doesn't change anything. 

My configuration uses what's recommended in the ibuffer-vc.el, and nothing else fancy.

**Comment by purcell** [comment]
Hmm. Which Emacs version do you have?

**Comment by purcell** [comment]
(I can reproduce this in Emacs 23.3, at least, though of course it's been working fine for me with a newer version.)

**Comment by purcell** [comment]
Reverting the change from 5 weeks ago (for #9) seems to fix the problem, but I'd like to figure out why before I undo that work.

**Comment by purcell** [comment]
Okay, I believe I've fixed this now in b2bac7a. Please re-open this issue if you still see any problems with the new version.

**Comment by wdenton** [comment]
Working. Thanks. So nice to have this back!

**Comment by purcell** [comment]
Sorry it got broken!
