### ISSUE TITLE
doesn't group

### ISSUE THREAD

**Issue by tihuang02** [purcell/ibuffer-vc#13]
Hi,

This is a great feature I'd like to use.

However, I installed version 20150714.1320 from elpa but it doesn't see to do anything. Everything is still under [Default] after 'ibuufer-vc-set-filter-groups-by-vc-root'. All my files are under some git repo.
I am using GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)

**Comment by purcell** [comment]
Works for me with the same ibuffer-vc and Emacs versions. I can start an empty Emacs, open a few files, run `ibuffer`, then load `ibuffer-vc.el`. Then, when I use `M-x ibuffer-vc-set-filter-groups-by-vc-root` everything gets grouped correctly. Please can you provide steps to reproduce the problem you're seeing?

**Comment by tihuang02** [comment]
Hmm,
I removed all my customization and started with a clean emacs run and tried it again. It works! So it must be something with my .emacs.

Thx for looking into this.
Daniel

**Comment by purcell** [comment]
No problem. Sorry I couldn't guess what might have been going wrong.
