### ISSUE TITLE
VC status is not updated frequently enough

### ISSUE THREAD

**Issue by ft** [purcell/ibuffer-vc#17]
I just started using ibuffer-vc and it seems to fit my workflow quite well.

I am using magit as well and I found the following:

- I am editing a file that's in version control.
- Then I am opening ibuffer with ibuffer-vc set up and enabled.
- The state comes up as "edited". Good.
- I switch back to the buffer with the file.
- Now I use `magit-status` stage the changes and commit them.
- I return to ibuffer but the state is still "edited" instead of "up-to-date".

I cannot seem to get it to update this piece of information properly.

I think `ibuffer-vc--status-string` should call `vc-refresh-state` so the
VC data is up to date. If I apply that change to make the function look
like this:

```
(defun ibuffer-vc--status-string ()
  "Return a short string to represent the current buffer's status."
  (when (and buffer-file-name (ibuffer-vc--include-file-p buffer-file-name))
    (vc-refresh-state)
    (let ((state (ibuffer-vc--state buffer-file-name)))
      (if state
          (symbol-name state)
        "-"))))
```

With this, I cannot seem to make the status appear off.

**Comment by purcell** [comment]
Thanks for getting in touch! Glad `ibuffer-vc` is helpful to you.

> I think ibuffer-vc--status-string should call vc-refresh-state so the
> VC data is up to date.

I disagree. If the vc-provided functions are not providing the correct status, that's a vc bug, or the fault of code elsewhere that is not forcing an update. As I understand it, magit already takes steps to keep the vc status up-to-date, so perhaps that is where the fault lies.

If I add `vc-refresh-state` to `ibuffer-vc` then it will potentially result in hundreds of additional expensive invocations of `git` & co, most of which should never be necessary, and this seems a bad trade-off.

So I'm going to close this issue, but I'd encourage you to check into why `magit` isn't updating the `vc` state for buffers in your configuration.

**Comment by ft** [comment]
Ah yes, indeed. I also just saw the pull request about this
from last year. I only tried with two git repositories active,
which is bound to be pretty quick on a local file system.

I can see how performance is a legitimate concern with
more complex situations. I will see if I can make progress
with the other involved parties (magit and vc).

Thanks for your quick response and your work on this.

**Comment by tarsius** [comment]
> As I understand it, magit already takes steps to keep the vc status up-to-date, so perhaps that is where the fault lies.

It doesn't. But this keeps coming up and I will attempt to come up with a solution. That won't happen anytime soon though. Also I don't think it will be enough to make sure that Magit calls the appropriate vc function when something might have changed. Things should also change on VC's side. But I don't have all the details in my head right now, and as I said I won't work on this soon.

Currently I recommend that Magit users disable VC for Git repositories, see https://github.com/magit/magit/wiki/magit-update-uncommitted-buffer-hook.
