### ISSUE TITLE
Group remains after all buffers killed

### ISSUE THREAD

**Issue by doolio** [purcell/ibuffer-vc#28]
If one marks and kills all the buffers under a particular group the group remains even after executing `ibuffer-update` or `ibuffer-auto-mode`. I would have expected the group to be removed when no buffers belonging to it exist anymore. Perhaps there is a way to achieve this with `auto-revert-mode`. Thanks for your time.

**Comment by doolio** [comment]
Had a look at your `init-ibuffer.el` and setting `ibuffer-show-empty-filter-groups` to `nil` does the trick. Sorry for the noise.

**Comment by purcell** [comment]
Glad you figured it out. :-)
