### ISSUE TITLE
Can't 'remove' the vc-setting in ibuffer

### ISSUE THREAD

**Issue by ouboub** [purcell/ibuffer-vc#29]
Hi

Once I either run ibuffer-vc-set-filter-groups-by-vc-root
or using the hook
   (add-hook 'ibuffer-hook
     (lambda ()
       (ibuffer-vc-set-filter-groups-by-vc-root)
       (unless (eq ibuffer-sorting-mode 'alphabetic)
         (ibuffer-do-sort-by-alphabetic))))
(I try to avoid the lambda function)

And then I decide not to use that filtering any more, it seems impossible to remove.
Ifbuffer always now use that filter. I have to restart emacs (running master compiled a month ago)
any idea what to do?

thanks

Uwe Brauer

**Comment by ouboub** [comment]
sorry, this is nonsense: I used q, which is quit window and not delete buffer as I should. sorry for the noise

**Comment by purcell** [comment]
No worries, glad you figured it out
