### ISSUE TITLE
not taking `.gitignore` into account

### ISSUE THREAD

**Issue by c-alpha** [purcell/ibuffer-vc#30]
This may not be possible for all version control systems, and I admittedly haven't checked whether VC in Emacs has any support for determining whether a given file is being ignored by version control, or not.

It would still be a nice treat to **not** see the ignored files in the VC group though.

**Comment by purcell** [comment]
I _think_ you could do this already. Something like:

```
(setq ibuffer-vc-include-function
  (lambda (f) (ignore-errors (not (eq 'ignored (vc-state f))))))
```

(untested)

**Comment by c-alpha** [comment]
Thanks!
