### ISSUE TITLE
Empty groups due to ephemeral buffers

### ISSUE THREAD

**Issue by ptrv** [purcell/ibuffer-vc#9]
When creating filter groups, the source is the output from `(buffer-list)`. This however returns all buffers, including ephemeral buffers not necessarily shown in `ibuffer` (this can be controlled with the variable `ibuffer-default-display-maybe-show-predicates`), which can lead to the creation of filter groups that has no 'visible' buffers if the ephemeral buffer has the `default-directory` to a path controlled by git.

In my case I have a buffer ` *code-converting-work*` whose default-diractory is the emacs source directory where I compiled emacs and it shows up as empty filter group by default.

It would be nice to filter the output of `(buffer-list)` to not include the `ibuffer-maybe-show-predicates` (ephemeral buffers). I noticed the same problem in `ibuffer-projectile`.

**Comment by purcell** [comment]
Can't you just set `ibuffer-show-empty-filter-groups` to nil?

**Comment by ptrv** [comment]
It is set to nil. That's the point. The empty group is still showing up.

**Comment by purcell** [comment]
Hrm. Okay, will investigate.

**Comment by purcell** [comment]
Can you test with this modified function definition please?

```el
(defun ibuffer-vc-generate-filter-groups-by-vc-root ()
  "Create a set of ibuffer filter groups based on the vc root dirs of buffers."
  (let ((roots (ibuffer-remove-duplicates
                (delq nil (mapcar (lambda (buf)
                                    (when (ibuffer-visible-p buf nil)
                                      (ibuffer-vc-root buf)))
                                  (buffer-list))))))
    (mapcar (lambda (vc-root)
              (cons (format "%s:%s" (car vc-root) (cdr vc-root))
                    `((vc-root . ,vc-root))))
            roots)))
```

**Comment by purcell** [comment]
Hang on, I don't think that's right.

**Comment by purcell** [comment]
Yeah, you know, this is a bit tricky, because `ibuffer` can optionally be told to redisplay showing all buffers, and `ibuffer-vc` will not always generate its groups at the same time that `ibuffer` is redisplaying. I'm not sure that this issue is really worth trying to fix...

**Comment by ptrv** [comment]
You haven't noticed the issue yourself, have you?

I am also not sure if it is worth fixing the issue if it is very tricky.

What I would like to know however what the `*code-conversion-work*` buffer is about and why it is set to the source folder I compiled Emacs in.

**Comment by purcell** [comment]
> You haven't noticed the issue yourself, have you?

No.

> I am also not sure if it is worth fixing the issue if it is very tricky.
> 
> What I would like to know however what the *code-conversion-work* buffer is about and why it is set to the source folder I compiled Emacs in.

I'm not sure. I've never seen that buffer before. :-/

**Comment by ptrv** [comment]
Strange. Probably I'll have to investigate what that buffer is about before applying any fix in ibuffer-vc.

Anyway, thanks for your investigation

**Comment by purcell** [comment]
If you figure out a fix, let me know. If it doesn't have any side-effects, I'd consider applying it to this repo.
